### ISSUE TITLE
Conflict with Better Chat Filter addon

### ISSUE THREAD

**Issue by Novarime** [FiftyCaliber/ToS-Addons#2]
for some reason, the filter censors the word "swap", causing all chat commands with "swap" in it to not work(/zplus swap 1 2, probably all Swap It commands)
i have tested it and found that i can't type the word "swap" after installing that filter, it gets replaced by "sw*p"
for now i can work around the issue by assigning two macros for zoomy plus(/zplus zoom 1 and zoom 2) instead of using swap, but you might want to have a talk with the better chat filter's creator about this since that add on renders your swapit add on entirely useless so i reported this(im not using swapit)
by the way i tested it on indonesian ToS

**Comment by FiftyCaliber** [comment]
I use Better Chat Filter v1.0.1 (most recent version on the Addon Manager) myself and do not have this issue. Either you are using a different version or the issue is unique to the Indonesian ToS?

**Comment by Novarime** [comment]
oh, apparently the word "swap" is censored now in indonesian ToS...... why the..
it's censored after 31st august major update here.
i have no idea why is swap even censored(i've tried "wap" and "swa" but they arent censored, so it really is the word "swap")
eh, well, so it's not an issue about conflict with chat filter
if you're not too lazy maybe you can consider adding an alternative command to swap? like switch or exchange, i tested it just now, both aren't censored

**Comment by FiftyCaliber** [comment]
Okay so I released Zoomy Plus v1.0.6 and Swapit v1.0.3 to deal with this issue.

Zoomy Plus:
`/zplus switch <num1> <num2>` added as an alternative slash command to swap.

Swapit:
`/si` `/si lock` `/si default` added as alternatives slash commands.

**Comment by Novarime** [comment]
thanks!
